# Generated by Django 5.2 on 2025-04-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='phone_number'),
        ),
    ]
