# Generated by Django 5.2 on 2025-04-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last_name')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='age')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date_of_birth')),
            ],
        ),
    ]
