# Generated by Django 5.2 on 2025-04-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_person_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone_number'),
        ),
        migrations.AlterModelTable(
            name='person',
            table='person',
        ),
    ]
