# Generated by Django 5.2 on 2025-04-23 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_person_phone_number_alter_person_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'get_latest_by': ['name', 'email']},
        ),
    ]
